---
title: "Paper Analysis"
author: "Nicholas Mikolajewicz"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r load XcalRep, message = F, warning = F}
rm(list = ls()) # clear enviroment
library(XcalRep)
library(dplyr)
```

```{r registered vs unregistered only}




df.invivo.unregistered <- invivo_unregistered
df.invivo.registered <- invivo_registered





df.invivo.unregistered$motionArtefact <- as.numeric(df.invivo.unregistered$motionArtefact)
df.invivo.unregistered <-  df.invivo.unregistered %>%
  dplyr::group_by(replicateSet) %>%
  dplyr::mutate(mean.ma = mean(motionArtefact)) %>%
  dplyr::ungroup()

df.invivo.unregistered <- as.data.frame(df.invivo.unregistered)
df.invivo.registered <- as.data.frame(df.invivo.registered)

all.data <- bind_rows(df.invivo.unregistered, df.invivo.registered)
# showTable(all.data, head.flag = T, as.dt = T) 

```


```{r}
# create calibration object using incomplete data input

rescan.var <- c("scanID", "parameter", "phantom", "site", "timePoint", "registration")

all.data$replicateSet <- defineReplicateSet(all.data, rescan.var)
df.invivo.registered$replicateSet <- defineReplicateSet(df.invivo.registered, rescan.var)
df.invivo.unregistered$replicateSet <- defineReplicateSet(df.invivo.unregistered, rescan.var)


# all.data$phantom[all.data$phantom == "radius"] <- "patient"
# all.data$phantom[all.data$phantom == "tibia"] <- "patient"

# df.invivo.registered$phantom[df.invivo.registered$phantom == "radius"] <- "patient"
# df.invivo.registered$phantom[df.invivo.registered$phantom == "tibia"] <- "patient"

# df.invivo.unregistered$phantom[df.invivo.unregistered$phantom == "radius"] <- "patient"
# df.invivo.unregistered$phantom[df.invivo.unregistered$phantom == "tibia"] <- "patient"


co.all <- createCalibrationObject(all.data)

co.reg <- createCalibrationObject(df.invivo.registered)
co.noreg <- createCalibrationObject(df.invivo.unregistered)

```




```{r these features}
# analyze.these <- analyzeWhich(co,
#                               omit.sections = "1",
#                               omit.sites = c("Odense", "Vanderbilt", "Aarhus", "Cambridge", "Southamptom", "WUSTL", "Baylor", "Paris", "Toronto", "Montreal", "Lyon"),
#                               include.parameters = "Tt.vBMD")

# analyze.these <- analyzeWhich(co,
#                               omit.sections = "1",
#                               omit.sites = c("Odense", "Vanderbilt", "Southamptom"))

# analyze.these <- analyzeWhich(co,
                              # omit.sections = "1",
                              # omit.sites = c("Odense", "Vanderbilt", "Aarhus"))

analyze.these.all <- analyzeWhich(co.all)
analyze.these.reg <- analyzeWhich(co.reg)
analyze.these.noreg <- analyzeWhich(co.noreg)
# str(analyze.these)

```




```{r preprocess data, warning = F}
co.all <- preprocessData(object = co.all, 
                      analyze.which = analyze.these.all, 
                      new.assay.name = "preprocessed.data",
                      which.assay = "input")

co.reg <- preprocessData(object = co.reg, 
                      analyze.which = analyze.these.reg, 
                      new.assay.name = "preprocessed.data",
                      which.assay = "input")

co.noreg <- preprocessData(object = co.noreg, 
                      analyze.which = analyze.these.noreg, 
                      new.assay.name = "preprocessed.data",
                      which.assay = "input")

# TODO
# What happens when multiple phantoms are alayzed together?
```




```{r svp analysis, warning = F, message = F}
co.all <- svpAnalysis(co.all, 
                   which.data = "uncalibrated",
                   verbose = F)

co.reg <- svpAnalysis(co.reg, 
                   which.data = "uncalibrated",
                   verbose = F)

co.noreg <- svpAnalysis(co.noreg, 
                   which.data = "uncalibrated",
                   verbose = F)
```


```{r get svp results}

# retrieve stored results (as datatables)
svp.results.uncalibrated.reg <-getResults(object = co.reg,
                                which.results = "svp")

svp.results.uncalibrated.noreg <-getResults(object = co.noreg,
                                which.results = "svp")

# see what tables were generated 
names(svp.results.uncalibrated.reg)

# show rms statistics
showTable(svp.results.uncalibrated.reg[["replicate.statistics"]], as.dt = T)
showTable(svp.results.uncalibrated.noreg[["replicate.statistics"]], as.dt = T)


a <- svp.results.uncalibrated.reg[["replicate.statistics"]]

b <- svp.results.uncalibrated.noreg[["replicate.statistics"]]
b <- b[b$n.scans>1, ]
b <- b[,c("scanID", "mean.ma", "timePoint", "phantom")]

# [,c("scanID", "mean.ma", "timePoint", "phantom")]

b <- unique(b)

d <- merge(a, b, by = c("scanID", "timePoint", "phantom"), all.x = T)


showTable(d, as.dt = T)

```


```{r}

meanVarPlot(co.reg,
            which.data = "uncalibrated",
            which.plot = "scatter",
            which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar",  "Tb.N", "Tb.Th", "Tb.Sp", "inhomogeneity.Tb.network","peripheral.medullary.Tb.BD",  "app.modulus", "stiffness", "failure.load"),
            point.size = 3
           )

meanVarPlot(co.reg,
           which.data = "uncalibrated",
           which.plot = "scatter",
           which.parameter = c("Ct.Po"),
           point.size = 3
           )

# co.noreg
# 
# meanVarPlot(co.noreg,
#             which.data = "uncalibrated",
#             outliers = F,
#             which.plot = "scatter",
#             which.phantom = "EFP")


# Note ENSURE THAT phantom replicate scans are properly grouped (e.g., for in vivo replicates)
```

```{r}
# showTable(svp.results.uncalibrated[["replicate.statistics"]])
```


```{r svp plot scanner, fig.width= 15, fig.height = 5, warning = F, message=F}
# 


# svpPlot(co,
#         which.data = "uncalibrated",
#         group.by = c("phantom"),
#         which.phantom = c("EFP", "patient"),
#         which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar"),
#         var2plot = "cv",
#         outliers = F,
#         color.begin = 0.1,
#         color.end = 0.5,
#         color.option = "cividis",
#         point.alpha = 1,
#         point.size = 3,
#         txt.size = 15,
#         jitter.width = 0.03,
#         color.begin.v2 = 0,
#         color.end.v2 = 1,
#         color.option.v2 = "viridis")

        # which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar"),

# "Ct.Po",  
# svpPlot(co,
#         which.data = "uncalibrated",
#         group.by = c("phantom"),
#         which.phantom = c("radius", "tibia"),
#         which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar", "Tb.BV/TV", "Tb.N", "Tb.Sp", "Tb.Th", "inhomogeneity.Tb.network",  "peripheral.medullary.Tb.BD", "app.modulus", "stiffness",  "failure.load"),
#         var2plot = "cv",
#         outliers = F,
#         color.begin = 0.5,
#         color.end = 1,
#         color.option = "cividis",
#         point.alpha = 1,
#         point.size = 3,
#         txt.size = 15,
#         jitter.width = 0.03,
#         color.begin.v2 = 0,
#         color.end.v2 = 1,
#         color.option.v2 = "viridis")


svpPlot(co.all,
        which.data = "uncalibrated",
        group.by = c("registration"),
        which.phantom = c("radius", "tibia"),
        which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar",  "Tb.N", "Tb.Th", "Tb.Sp", "inhomogeneity.Tb.network","peripheral.medullary.Tb.BD",  "app.modulus", "stiffness", "failure.load"),
        var2plot = "cv",
        outliers = F,
        color.begin = 0.5,
        color.end = 1,
        color.option = "cividis",
        point.alpha = 1,
        point.size = 2,
        txt.size = 15,
        jitter.width = 0.03,
        color.begin.v2 = 0,
        color.end.v2 = 1,
        color.option.v2 = "viridis")

svpPlot(co.noreg,
        which.data = "uncalibrated",
        group.by = c("oi"),
        which.phantom = c("radius", "tibia"),
        which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar",  "Tb.N", "Tb.Th", "Tb.Sp", "inhomogeneity.Tb.network","peripheral.medullary.Tb.BD",  "app.modulus", "stiffness", "failure.load"),
        var2plot = "cv",
        outliers = F,
        color.begin = 0.5,
        color.end = 1,
        color.option = "cividis",
        point.alpha = 1,
        point.size = 2,
        txt.size = 15,
        jitter.width = 0.03,
        color.begin.v2 = 0,
        color.end.v2 = 1,
        color.option.v2 = "viridis")


svpPlot(co.all,
        which.data = "uncalibrated",
        group.by = c("registration"),
        which.phantom = c("radius", "tibia"),
        which.parameter = c("Ct.Po"),
        var2plot = "cv",
        outliers = F,
        color.begin = 0.5,
        color.end = 1,
        color.option = "cividis",
        point.alpha = 1,
        point.size = 2,
        txt.size = 15,
        jitter.width = 0.03,
        color.begin.v2 = 0,
        color.end.v2 = 1,
        color.option.v2 = "viridis")
# CtPo_invivo_CSA_oi

 # c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar",  "Tb.N", "Tb.Th", "inhomogeneity.Tb.network","peripheral.medullary.Tb.BD",  "app.modulus", "stiffness", "failure.load")

        # which.parameter = c("Tt.vBMD", "Tb.vBMD", "Ct.vBMD.XCT2", "Ct.Th.XCT2", "Ct.Ar.XCT2", "Tb.Ar", "Tt.Ar"),

 
# "app.modulus" "stiffness"  "failure.load"

# RESUME HERE
```




